server.port=8081

spring.application.name=auth-service

# Default local profile: H2 Database
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis config with connection error tolerance
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500ms

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT configuration keys
prymo.auth.secret-key=PrymoSecureHoldBankingBackendJWTSecretSuperSecretKey123PrymoSecureHoldBankingBackendJWTSecretSuperSecretKey123
prymo.auth.token-expiration-ms=86400000

twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.from-number=${TWILIO_FROM_NUMBER:}

#---
# Production Profile: PostgreSQL + Kafka/Redis Container Deployment
spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:postgresql://postgres:5432/prymo_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
