server.port=8082

spring.application.name=account-service

# Default local profile: H2 Database
spring.datasource.url=jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

paystack.secret-key=${PAYSTACK_SECRET_KEY:}

#---
# Production Profile: PostgreSQL
spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:postgresql://postgres:5432/prymo_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
